credit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('courses/', include('courses.urls', namespace='courses')),
	path('templates/myapp/membership_list', include('myapp.urls', namespace='myapp')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from .views import MembershipSelectView, paymentView, update_transactions, profile, cancel_subscription

app_name = 'myapp'

urlpatterns = [
	path('', MembershipSelectView.as_view(), name='select'),
	path('payment/', paymentView, name='payment'),
	path('update-transactions/<subscription_id>/', update_transactions, name='update-transactions'),
	path('profile/', profile, name='profile'),
	path('cancel_subscription/', cancel_subscription, name='cancel_subscription'),
]

courses/models.py
from django.db import models
from django.urls import reverse
from myapp.models import Membership


# Create your models here.

class Course(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=40)
	description = models.TextField()
	allowed_membership = models.ManyToManyField(Membership)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:detail', kwargs={'slug': self.slug})

	@property
	def lessons(self):
		return self.lessons_set.all().order_by(
			'position')  # syntax for foreign key object grab all the lessons associated with it.


class Lessons(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=40)
	course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
	position = models.IntegerField()
	video_url = models.CharField(max_length=250)
	thumbnail = models.ImageField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:lesson_detail',
		               kwargs={'course_slug': self.course.slug, 'lesson_slug': self.slug})

myapp/models.py
import datetime
import stripe
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

stripe.api_key = settings.STRIPE_SECRET_KEY
# Create your models here.
MEMBERSHIP_CHOICES = (
	('Enterprise', 'ent'),
	('Professional', 'pro'),
	('Free', 'free'),
	('Amateur', 'amateur'),
)


class Membership(models.Model):
	slug = models.SlugField()
	membership_type = models.CharField(choices=MEMBERSHIP_CHOICES, default='Free', max_length=50)
	price = models.IntegerField(default=15)
	stripe_plan_id = models.CharField(max_length=50)

	def __str__(self):
		return self.membership_type


class UserMembership(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	stripe_customer_id = models.CharField(max_length=50)
	membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.user.username


def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
	if created:
		UserMembership.objects.get_or_create(user=instance)

	user_membership, created = UserMembership.objects.get_or_create(user=instance)

	if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
		new_customer_id = stripe.Customer.create(email=instance.email)
		user_membership.stripe_customer_id = new_customer_id['id']
		user_membership.save()


post_save.connect(post_save_usermembership_create, sender=settings.AUTH_USER_MODEL)


class Subscription(models.Model):
	user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
	stripe_subscription_id = models.CharField(max_length=50)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.user_membership.user.username

	@property
	def get_created_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.created)

	@property
	def get_next_billing_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.current_period_end)

myapp/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.urls import reverse

from .models import Membership, UserMembership, Subscription

import stripe


# Create your views here.
def profile(request):
	context = {}
	user_membership = get_user_membership(request)
	selected_membership = get_selected_membership(request)

	context['user_membership']: user_membership
	context['selected_membership']: selected_membership

	return render(request, '../templates/myapp/profile.html', context)


def get_user_membership(request):
	user_membership_qs = UserMembership.objects.filter(user=request.user)
	if user_membership_qs.exists():
		return user_membership_qs.first()
	return None


def get_user_subscription(request):
	user_subscription = Subscription.objects.filter(user_membership=get_user_membership(request))
	if user_subscription.exists():
		return user_subscription
	return None


def get_selected_membership(request):
	membership_type = request.session['selected_membership']
	selected_membership_type_qs = Membership.objects.filter(membership_type=membership_type)
	if selected_membership_type_qs.exists():
		return selected_membership_type_qs.first()
	return None


class MembershipSelectView(ListView):
	model = Membership

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(**kwargs)
		current_membership = get_user_membership(self.request)
		context['current_membership'] = str(current_membership.membership)
		return context

	def post(self, request, **kwargs):
		selected_membership_type = request.POST.get('membership_type')

		user_membership = get_user_membership(request)
		user_subscription = get_user_subscription(request)

		selected_membership_qs = Membership.objects.filter(membership_type=selected_membership_type)

		if selected_membership_qs.exists():
			selected_membership = selected_membership_qs.first()

		'''
		======
		VALIDATION
		======
		'''
		if user_membership == selected_membership:
			if user_subscription is not None:
				messages.info(request, 'You already subscribed ot this membership. Your payment is due on {}'.format(
					'get value from stripe'))
				return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		# assign to session
		request.session['selected_membership'] = selected_membership.membership_type

		return HttpResponseRedirect(reverse('myapp:payment'))


def paymentView(request):
	user_membership = get_user_membership(request)
	print('membership', user_membership.stripe_customer_id)

	selected_membership = get_selected_membership(request)
	print('PLAN', selected_membership.stripe_plan_id)
	publish_key = settings.STRIPE_PUBLISHABLE_KEY

	if request.method == 'POST':
		print(request.method)

		try:
			token = request.POST['stripeToken']
			print(token)

			source_var = stripe.Source.modify(token,
			    metadata={"plan": selected_membership.stripe_plan_id}, )
			print(source_var)

			subscription = stripe.Subscription.create(
				customer=user_membership.stripe_customer_id,
				items=[{'plan': selected_membership.stripe_plan_id, }],

			)

			return redirect(reverse('myapp:update-transactions',
			                        kwargs={
				                        'subscription_id': subscription.id
			                        }))

		except stripe.error.InvalidRequestError as e:
			print(stripe.Card)
			print('error: ', e)
			print('Status is: %s' % e.http_status)
			print('Type is: %s' % e.error.type)
			print('Code is: %s' % e.error.code)
			# param is '' in this case
			print('Param is: %s' % e.error.param)
			print('Message is: %s' % e.error.message)
			messages.info(request, 'Your card has been declined.')


	context = {
		'publishKey': publish_key,
		'selected_membership': selected_membership
	}

	return render(request, 'myapp/membership_payment.html', context)


def update_transactions(request, subscription_id):
	user_membership = get_user_membership(request)
	selected_membership = get_selected_membership(request)

	user_membership.membership = selected_membership
	user_membership.save()

	sub, created = Subscription.objects.get_or_create(user_membership=user_membership)
	sub.stripe_subscription_id = subscription_id
	sub.active = True
	sub.save()

	try:
		del request.session['selected_membership']
	except:
		pass
	messages.info(request, 'Successfully created {} membership'.format(selected_membership))
	return redirect('/courses')


def cancel_subscription(request):
	user_sub = get_user_subscription(request)

	if user_sub.active is not True:
		messages.info(request, "You don't have an active subscription.")
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
	sub.delete()

	user_sub.active = False
	user_sub.save()

	free_membership = Membership.objects.filter(membership_type='Free').first()
	user_membership = get_user_membership(request)
	user_membership.membership = free_membership
	user_membership.save()

	messages.info(request, 'Successfully canceled subscription.')

	return redirect('/myapp')

templates/myapp/membership_list.html
{% extends 'courses/base.html' %}

{% block content %}
    <div class="container">
        <h1>Select Membership</h1>
        <div class="row">
            {% for object in membership_list %}
                <div class="col-md-3 col-sm-3">
                    <h2>{{ object.membership_type }}</h2>
                    <p>Price: ${{ object.price }}
                        <small>/month</small>
                    </p>
                    <h4>Course Items</h4>
                    <ul>
                        {% for course in object.course_set.all %}
                            <li>{{ course.title }}</li>
                        {% endfor %}
                    </ul>
                    {% if object.membership_type != 'Free' %}
                        <form action="" method="post">
                            {% csrf_token %}
                            {% if object.membership_type != current_membership %}
                                <button type="submit" class="btn btn-warning">Select</button>
                            {% else %}
                                <small>This is your current membership.</small>
                            {% endif %}
                            <input type="hidden" value="{{ object.membership_type }}" name="membership_type">
                        </form>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}

templates/myapp/membership_payment.html
{% extends 'courses/base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">
    <div class="container">
        <h1>Payment</h1>
        <div class="col-md-4 col-sm-4">
            <p>Selected Memberhsip: {{ selected_membership }}</p>
            <button onclick="toggleDisplay();" class="btn btn-warning" style="width: 100%;">Checkout with a credit
                card
            </button>

            <div id="collapseStripe" class="wrapper" style="padding-top: 20px;">
                <script src="https://js.stripe.com/v3/"></script>

                <!-- can't do this -->
                <!-- <script src="{% static 'js/stripeV3.js' %}"></script> -->

                <form action="" method="post" id="payment-form">
                    {% csrf_token %}
                    <div class="form-row" style="margin-top: 30px;">
                        <label for="card-element">
                            Credit or debit card
                        </label>
                        <div id="card-element" class="StripeElement StripeElement--empty">
                            <div class="__PrivateStripeElement"
                                 style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                                <iframe frameborder="0" allowtransparency="true" scrolling="no"
                                        name="__privateStripeFrame3" allowpaymentrequest="true"
                                        src="https://js.stripe.com/v3/elements-inner-card-8a434729e4eb82355db4882974049278.html#style[base][color]=%2332325d&amp;style[base][lineHeight]=18px&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;features[noop]=false&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js%2Felements%2Fquickstart&amp;controllerId=__privateStripeController0"
                                        title="Secure payment input frame"
                                        style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; height: 18px;"></iframe>
                                <input class="__PrivateStripeElement-input" aria-hidden="true"
                                       style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;"><input
                                    class="__PrivateStripeElement-safariInput" aria-hidden="true" tabindex="-1"
                                    style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                            </div>
                        </div>
                        <button>Submit Payment</button>
                        <!-- Used to display form errors. -->
                        <div id="card-errors" role="alert"></div>
                    </div>


                </form>

            </div>

        </div>

        <div id="stripe-token-handler" class="is-hidden">Success! Got token: <span class="token"></span></div>


    </div>
    </div>
    </div>


    <!-- script for the stripe form -->
    <script src="{% static 'js/checkout.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>

    <!-- script for toggling display of the form -->
    <script type="text/javascript">
        function toggleDisplay() {
            var x = document.getElementById("collapseStripe");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        };
    </script>

    </div>

    </div>
{% endblock %}

templates/myapp/profile.html
{% extends 'courses/base.html' %}

{% block content %}
    <div class="container">
        <h1>My Profile</h1>
        <div class="col-md-6 col-sm-6">

            {% if user_subscription is not None %}
                <h4>Current Membership: {{ user_membership.membership.membership_type }}
                    <small>since: {{ user_subscription.get_created_date }}</small>
                </h4>

                {% if user_subscription.active != False %}
                    <p>Next Payment due: {{ user_subscription.get_next_billing_date }}</p>
                    <a href="{% url 'myapp:cancel_subscription' %}">
                        <button class="btn btn-sm btn-danger">Cancel Subscription</button>
                    </a>
                {% endif %}
            {% else %}
                <p>You don't have any active subscription.
                    <a href="{% url 'myapp:select' %}">Check them out here.</a>
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}