courses/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, LessonDetailView

app_name = 'courses'
urlpatterns = [
	path('', CourseListView.as_view(), name='list'),
	path('<slug>', CourseDetailView.as_view(), name='detail'),
	path('<course_slug>/<lesson_slug>', LessonDetailView.as_view(), name='lesson_detail'),
]

credit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('courses/', include('courses.urls', namespace='courses')),
	path('templates/myapp/membership_list', include('myapp.urls', namespace='myapp')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from .views import MembershipSelectView, paymentView, update_transactions, profile, cancel_subscription

app_name = 'myapp'

urlpatterns = [
	path('', MembershipSelectView.as_view(), name='select'),
	path('payment/', paymentView, name='payment'),
	path('update-transactions/<subscription_id>/', update_transactions, name='update-transactions'),
	path('profile/', profile, name='profile'),
	path('cancel_subscription/', cancel_subscription, name='cancel_subscription'),
]

courses/models.py
from django.db import models
from django.urls import reverse
from myapp.models import Membership


# Create your models here.

class Course(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=40)
	description = models.TextField()
	allowed_membership = models.ManyToManyField(Membership)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:detail', kwargs={'slug': self.slug})

	@property
	def lessons(self):
		return self.lessons_set.all().order_by(
			'position')  # syntax for foreign key object grab all the lessons associated with it.


class Lessons(models.Model):
	slug = models.SlugField()
	title = models.CharField(max_length=40)
	course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
	position = models.IntegerField()
	video_url = models.CharField(max_length=250)
	thumbnail = models.ImageField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('courses:lesson_detail',
		               kwargs={'course_slug': self.course.slug, 'lesson_slug': self.slug})

courses/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View

from myapp.models import UserMembership
from .models import Course, Lessons


# Create your views here.

class CourseListView(ListView):
	model = Course


class CourseDetailView(DetailView):
	model = Course


class LessonDetailView(View):

	def get(self, request, course_slug, lesson_slug, *args, **kwargs):
		context = {}
		course_qs = Course.objects.filter(slug=course_slug)

		if course_qs.exists():
			course = course_qs.first()

		lesson_qs = course.lessons.filter(slug=lesson_slug)

		if lesson_qs.exists():
			lesson = lesson_qs.first()

		user_membership = UserMembership.objects.filter(user=request.user).first()
		user_membership_type = user_membership.membership.membership_type
		courses_allowed_mem_type = course.allowed_membership.all()

		print('user_membership_type', user_membership_type)
		print('courses_allowed_mem_type', courses_allowed_mem_type)

		context['lesson'] = None
		if courses_allowed_mem_type.filter(membership_type=user_membership_type).exists():
			print('courses_allowed_mem_type', courses_allowed_mem_type)
			context['lesson'] = lesson
		return render(request, 'courses/lesson_detail.html', context)

templates/courses/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <title></title>
    {#    <link rel="stylesheet" href="{% static_root 'admin/css/base.css' %}">#}
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"#}
{#          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">#}

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

</head>
<body>
{% include 'courses/messages.html' %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 m-0, p-0">

            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'myapp:profile' %}">Profile</a></li>
                    {% block pos_detail_link %}{% endblock %}

                    {% if not request.user.is_authenticated %}
                        <li class="float-right breadcrumb-item"><a href="/register">Register</a></li>
                        <li class="float-right breadcrumb-item"><a href="/login">Login</a></li>
                    {% else %}
                        <li class="float-right breadcrumb-item"><a href="{% url 'myapp:select' %}">Memberships</a></li>
                    {% endif %}
                </ol>

            </div>
            {% block content %}{% endblock content %}
        </div>

    </div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/courses/course_detail.html
{% extends 'courses/base.html' %}
{% block content %}
    <div class="container">
        {{ object.title }}
        {% for lesson in object.lessons %}
            <a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a>
            </div>

        {% endfor %}

{% endblock %}

templates/courses/course_list.html
{% extends 'courses/base.html' %}
{% block content %}

    <div class="container">
        <h1>All Courses</h1>
        {% for course in object_list %}
            <a href="{{ course.get_absolute_url }}">{{ course }}</a>
        {% endfor %}

    </div>

{% endblock %}

templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}

{% block content %}
    <div class="container">
        <h1>All Lessons</h1>
        {% if lesson is not None %}
            {{ lesson.title }}
            {{ lesson.description }}
        {% else %}
            <h3>Upgrade Your Membership</h3>
        {% endif %}

    </div>

{% endblock %}

templates/courses/messages.html
{% if messages %}
    <style type="text/css">
        div.messages{
            background-color: #ff6b6b;
            color: #f7fff7;
        }
        ul.messages{
            list-style-type: none;
        }
    </style>

    <div class="messages">
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %}class="{{ message.tags }}" {% endif %}>
            {% if "html_safe" in message.tags %}
                {{ message|safe }}
                {% else %}
                {{ message }}
            {% endif %}
            </li>
        {% endfor %}
    </ul>
    </div>
{% endif %}